blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/muhittincamdali/iOS-Security-Framework-Pro#readme
    about: Check out the documentation first
  - name: ðŸ’¬ Discussions
    url: https://github.com/muhittincamdali/iOS-Security-Framework-Pro/discussions
    about: Ask questions and discuss ideas
